spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: ${spring.profile:local}

legacy:
  ingration:
    url: https://www.cielo.com.br
    
cors.origins:
  ${ENDPOINT_FRONT:http://localhost:4200}